# Generated by Django 5.0.6 on 2024-07-03 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0006_confessdata_like_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confessdata',
            name='like_count',
        ),
        migrations.AddField(
            model_name='confessdata',
            name='liked_by',
            field=models.ManyToManyField(related_name='confesslike', to=settings.AUTH_USER_MODEL),
        ),
    ]
