# Generated by Django 5.0.6 on 2024-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three', '0005_confessdata_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessdata',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
